version: "3"

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: omero
      POSTGRES_PASSWORD: omero
      POSTGRES_DB: omero
    volumes:
      - omero_postgres_data:/var/lib/postgresql/data
    networks:
      - omero

  omero-server:
    image: openmicroscopy/omero-server:5.6
    environment:
      CONFIG_omero_db_host: postgres
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero-root-password
    ports:
      - "4064:4064"
    volumes:
      - omero_data:/OMERO
    networks:
      - omero
    depends_on:
      - postgres

  omero-web:
    image: openmicroscopy/omero-web-standalone:5.6
    environment:
      OMEROHOST: omero-server
    ports:
      - "4080:4080"
    networks:
      - omero
    depends_on:
      - omero-server

networks:
  omero:

volumes:
  omero_postgres_data:
  omero_data:

